### ISSUE TITLE
index names looks not used

### ISSUE THREAD

**Issue by solisoft** [paktek123/elasticsearch-crystal#4]
Here my code : 
```require "kemal"
require "elasticsearch-crystal/elasticsearch/api"

client = Elasticsearch::API::Client.new({:host => "elasticsearch", :port => 9200})

get "/" do |env|
  env.response.content_type = "application/json"
  client.search({:index => "product_index", :q => "wax"}).to_json
end

Kemal.run
```

But I have this error : 
```
{
  error: "Incorrect HTTP method for uri [/_all/_all?index=_all&q=wax&type=&fields=&fielddata_fields=] and method [GET], allowed: [POST]",
  status: 405
}
```

What's wrong ? I should see my index name in the url right ? 

I checked my `product_index` key with `client.indices.get({ :index => "product_index" }).to_json` and it went well

**Comment by solisoft** [comment]
By the way I use elastic search 6.4.1

**Comment by paktek123** [comment]
Thanks for opening the issue. I haven't had the chance to test this library out with Elasticsearch version 6.4.1 so the API might have changed. I will need to dig further to debug this. I'll get back to you.

**Comment by paktek123** [comment]
ok I have confirmed this is a bug

**Comment by paktek123** [comment]
this has been fixed in https://github.com/paktek123/elasticsearch-crystal/pull/5. Please open another issue if there are further problems. Please remember that elasticsearch 6.4.1 api is not fully supported yet. Please upgrade to 0.14.
